### ISSUE TITLE
I'm really confused about how to use plugins.

### ISSUE THREAD

**Issue by imcaffrey** [GitbookIO/plugin-mathjax#12]
The help doc didn't help very much here.

I added this into my `book.json`:

```
{
   plugins: ["katex"]
}
```

but the build failed, so I changed into this:

```
{
    "plugins": ["katex"]
}
```

again it did not work, telling me that

```
info: load plugin katex ....ERROR
Error: Error loading plugins: katex. Run 'gitbook install' to install plugins from NPM.
```

So what exactly should I be doing to enable MathJax for my doc?

Thanks again for this great system.

**Comment by SamyPesse** [comment]
This plugin is `mathjax`, not `katex`.

You did the right thing, but like the message is telling you, you need to run `gitbook install` to download plugins.
