### ISSUE TITLE
inline formula notation issue

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [GitbookIO/plugin-mathjax#15]
I wonder why the inline formula notation `$$...$$` is different with [math mode - Inline equation in latex with text - TeX - LaTeX Stack Exchange](http://tex.stackexchange.com/questions/52276/inline-equation-in-latex-with-text) `$...$`

**Comment by cben** [comment]
[not a gitbook dev, just providing context]

The problem everybody runs into with `$` is false positives — texts like `It costs between $20 and $37` occur naturally and having them turn into math unless escaped would be annoying to users who don't need math, and incompatible to the original markdown (well, any syntax extension is _technically_ incompatible but  _practically_ the question is whether many or few existing documents change meaning).  
There are many solutions to this, eg. constraining `$` with heuristics (e.g. closing $ not followed by digit and not under full moon), using `\(` / `\[` (which interfere with escaping some markdown syntaxes) or `\\(` / `\\[` instead, etc.  
Using `$$` for both inline and display was I believe an invention of kramdown, and is one of the prettier solutions.  There is interesting critique on https://github.com/GitbookIO/kramed/issues/3 however that it prevents conveying when display math is part of a larger "semantic paragraph" (a concept mostly ignored by Markdown but easily expressed in LaTeX).
And `{% math %}...{% endmath %}` is of course modeled on Gitbook templating constructs.

FWIW, I'm cataloging math in markdown syntaxes at https://github.com/cben/mathdown/wiki/math-in-markdown

**Comment by pkra** [comment]
> FWIW, I'm cataloging math in markdown syntaxes at https://github.com/cben/mathdown/wiki/math-in-markdown

@cben that's very useful! Thanks for sharing this.

**Comment by SamyPesse** [comment]
@cben Awesome answer :+1: 

With GitBook, inline math are differentiated from block math [using the first character](https://github.com/GitbookIO/plugin-mathjax/blob/master/index.js#L59), example:

```md
Some inline math $$a = b$$

And a block of math:

$$
a = b
$$
```

**Comment by cben** [comment]
I like that!  2 late questions:

1. If there are trailing spaces between the opening $$ and the newline it becomes inline.  IMHO surprising, should be still block.

2. It seems that's specific to GitBook plugins, kramed itself still uses [same regex as kramdown, essentially `/^ *$$...$$ *\n/`](https://github.com/GitbookIO/kramed/blob/8c099547b7541bf8e4759489f02889d82c64f9f7/lib/rules/block.js#L28) (sounds like should be alone on a *line*, but I [tested kramdown][babel] and it actually must be alone in paragraph, [as documented](http://kramdown.gettalong.org/syntax.html#math-blocks), there is probably extra logic...).  Right?

    Given that kramed is "your" fork, any plans to match gitbook rule, or will you keep the kramdown rule?

[babel]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%24%24inline%24%24+with+other+text%0A%0A%24%24%0Ablock%0A%24%24+%0A%0A%24%24+%0A%5Ctext%7Bspace+after+opening+dollars+%3D%3E+not+block%3F%7D%0A%24%24%0A%0Aline+vs+block+boundary+test%3A+text+before%0A%24%24block%3F%24%24%0A%0A%24%24block%3F%24%24%0Atext+after+(line+vs+block+boundary+test)

**Comment by weihuayi** [comment]
For the inline math, does there exist any way to reset it to `$ .... $` in gitbook?  I find  `$$ ... $$` annoy me very much when I want to copy markdown to latex or other place.

**Comment by yoczhang** [comment]
> For the inline math, does there exist any way to reset it to `$ .... $` in gitbook? I find `$$ ... $$` annoy me very much when I want to copy markdown to latex or other place.

Have you found the right way? @weihuayi

**Comment by weihuayi** [comment]
我尝试解决过这个问题，但一直没有成功。


 
---Original---

**Comment by weihuayi** [comment]
可以先把 markdown 转成 latex 试试


 
---Original---
