### ISSUE TITLE
upgrade to 2.6

### ISSUE THREAD

**Issue by nagim** [GitbookIO/plugin-mathjax#19]
Hi,

There is a bug in the <2.6 mathjax versions, where there's a trailing | rendered in Chrome at the end of the formulas.
An upgrade to 2.6 would eliminate the issue (and the need to hide it with CSS rules).

Thanks,
Imre

**Comment by SamyPesse** [comment]
The last version of the plugin uses MathJax 2.6, you can even configure it: https://github.com/GitbookIO/plugin-mathjax/blob/master/package.json#L34

**Comment by nagim** [comment]
Thanks, I will try to force the version, because if I check the formula in the browser, it reports mathjax 2.5.3.

**Comment by nagim** [comment]
Tried to force the version, but from the build log, it seems that v2.5.1 is used despite of that:

```
info: install plugin mathjax from npm (gitbook-plugin-mathjax) with version 1.0.2 
make: Entering directory `/tmp/book/node_modules/gitbook-plugin-mathjax/node_modules/MathJax-node/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
  COPY Release/contextify.node
make: Leaving directory `/tmp/book/node_modules/gitbook-plugin-mathjax/node_modules/MathJax-node/node_modules/jsdom/node_modules/contextify/build'
gitbook-plugin-mathjax@1.0.2 node_modules/gitbook-plugin-mathjax
├── crc@3.2.1
├── q@1.1.2
└── MathJax-node@0.3.0 (yargs@4.7.0, speech-rule-engine@0.9.2, MathJax@2.5.1-mjnode, jsdom@3.1.1)
```

Was using GitBook 2.6.7.

**Comment by pkra** [comment]
Just a side note: MathJax-node was renamed mathjax-node a while back (and thus is stuck at 0.3 whereas mathjax-node is at 0.5.1).

**Comment by nagim** [comment]
@SamyPesse, could you please update the package name, so we can use the latest version?

Thanks a lot!

Cheers,
Imre
