### ISSUE TITLE
Gitbook fails to build after version 1.1.1

### ISSUE THREAD

**Issue by vkrishna143** [GitbookIO/plugin-mathjax#21]
Hey,
Gitbook builds properly with  mathjax version 1.1.0
But with mathjax version 1.1.1, I am getting a error 
"PluginError: Error with plugin "mathjax": Cannot find module 'MathJax-node/lib/mj-single.js' "

**Comment by pkra** [comment]
I suspect https://github.com/GitbookIO/plugin-mathjax/blob/master/index.js#L6 needs to update to the new capitalization (`mathjax-node`).

**Comment by jpreynat** [comment]
Sorry @vkrishna143 and thanks @pkra.
This is has been fixed by c79500cd9bfa471ad83e94a90113b97e64d9d712.
npm package has been published to `gitbook-plugin-mathjax@1.1.2`.

**Comment by vkrishna143** [comment]
Thanks @jpreynat ..
Its working fine now.

**Comment by jpreynat** [comment]
Thanks for your feedback, I'm glad to hear it!
Have a nice day.

Kind regards,
Johan
